spring:
  jpa:
    hibernate:
      ddl-auto: none
  messages:
    basename: messages/messages
    encoding: UTF-8

logging:
  level:
    org.springframework.web: ERROR
    com.example: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%C] - %msg%n"